### PR TITLE
Support for meta-environment

### PR DESCRIPTION
**Pull request by Mte90**
The meta environment template does'nt use the hosts parameters and without that patch the vvv.test page show a lot of php errors.

### CODE REVIEW

**Comment by tomjn** [comment]
I don't think we should make special cases for the meta environment, and just handle when no hosts are specified, and show that as a warning

**Comment by Mte90** [comment]
immagine

**Comment by tomjn** [comment]
Not all meta environments are going to be named `wordpress-meta-environment`, and not all non-meta sites have hosts defined, we can't hardcode names to fix bugs

**Comment by tomjn** [comment]
e.g. this site would reproduce that error without being the meta environment:

```yaml
  testsite:
    description: "PHP warnings"
    skip_provisioning:false
```

**Comment by tomjn** [comment]
The fix is that if `$site['hosts']` is empty, don't run `array_reduce` etc

**Comment by Mte90** [comment]
I will work on that fix.

**Comment by Mte90** [comment]
Now check for the status of that array instead like before.

**Pull request merged**
