### PR TITLE
WIP: React dash

### PR DESCRIPTION
**Pull request by tomjn**
Changes the dashboard to use a React powered sites list and adds various NPM things

### CODE REVIEW

**Comment by cfoellmann** [comment]
:thumbsup: 
Will Test asap

**Comment by tomjn** [comment]
current status:

screen shot 2018-06-27 at 20 13 14

**Comment by tomjn** [comment]
Styling Updates

screen shot 2018-06-27 at 21 09 57

**Comment by tomjn** [comment]
Now with icons and folder location, all that needs adding for feature parity is the warnings for .local and .dev domains
screen shot 2018-06-28 at 14 53 51

**Comment by tomjn** [comment]
I'm going to close this out, it's useful to have this code but I don't believe this is the way to implement a react dashboard any more

**Pull request closed without merging**
